### ISSUE TITLE
метод LoadControllerClassFromFile не учитывает параметры входящие в конструктор 

### ISSUE THREAD

**Issue by antonshevelev** [pozitronik/yii2-helpers#4]
За `DI` забыли :(
https://www.yiiframework.com/doc/api/2.0/yii-baseyii#createObject()-detail

**Comment by antonshevelev** [comment]
На PR прав не хватает 
<img width="1227" alt="Снимок экрана 2022-05-16 в 20 07 32" src="https://user-images.githubusercontent.com/10631259/168646470-e6b5111f-c4ee-4630-a27d-3df605cdf251.png">

**Comment by pozitronik** [comment]
> На PR прав не хватает

Это через форк делается.
+ я запилил тесты, буду понемногу накидывать, а к добавляемому ты тоже пиши.
